### ISSUE TITLE
Remote builders broken

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuporter#117]
It looks like the local builders (68e3958c02b5cb92fb6c6511b53bcb745a739019) change broke the remote builders feature.

```
app-arch::zstd-1.1.2
======================================================================
Checking if package dependencies need to be updated ...
    updating dependency infos of zstd-1.1.2
The following built dependencies were found:
Exception in thread build 0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kallisti5/Code/haikuporter/HaikuPorter/BuildMaster.py", line 941, in _buildThread
    (buildSuccess, reschedule) = builder.runBuild()
  File "/home/kallisti5/Code/haikuporter/HaikuPorter/BuildMaster.py", line 380, in runBuild
    except (IOError, paramiko.ssh_exception.SSHException) as exception:
NameError: global name 'paramiko' is not defined
```

**Comment by kallisti5** [comment]
It appears the later import of paramiko doesn't offer it up to portions of the code.  Seems resolved after moving the attempted import back to the top.
