### ISSUE TITLE
Unknown path 'stub' in buildmaster mode

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuporter#124]
Seeing this after upgrading the buildmasters.  It could be due to my change of behaviour around --no-dependencies being default.. however findDirectory shouldn't return 'stub' on Haiku platforms... so not sure yet.

```
Running patch function ...
Committing changes done in patch function for cdrtools-3.02a07.tar.bz2
Traceback (most recent call last):
  File "/app/haikuporter/HaikuPorter/Main.py", line 39, in __init__
    self.run(args)
  File "/app/haikuporter/HaikuPorter/Main.py", line 402, in run
    self._buildPort(port, True, self.packagesPath)
  File "/app/haikuporter/HaikuPorter/Main.py", line 625, in _buildPort
    port.build(self.packagesPath, self.options.package, targetPath)
  File "/app/haikuporter/HaikuPorter/Port.py", line 751, in build
    buildPlatform.findDirectory('B_SYSTEM_PACKAGES_DIRECTORY'))
  File "/app/haikuporter/HaikuPorter/RequiresUpdater.py", line 46, in addPackages
    for package in os.listdir(directory):
OSError: [Errno 2] No such file or directory: 'stub'
build master failed
```

**Comment by kallisti5** [comment]
resolved by inverting the no-dependencies behavior via new --all-dependencies flag.
We likely should look at why findDirectories is returning 'stub' when B_FIND_DIRECTORY fails... that design really smells.
