### ISSUE TITLE
get-dependencies fails under latest haikuporter

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuporter#148]
```
/Data/haikuporter> ./haikuporter --get-dependencies --debug huexpress
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
Checking if package dependencies need to be updated ...
        updating dependency infos of huexpress-3.0.4
----------------------------------------------------------------------
games-emulation::huexpress-3.0.4
        /Data/haikuports/games-emulation/huexpress/huexpress-3.0.4.recipe
----------------------------------------------------------------------
Skipping download of source for 3.0.4.tar.gz
Skipping checksum validation of 3.0.4.tar.gz
Skipping unpack of 3.0.4.tar.gz
Cleaning up temporary directories ...
Traceback (most recent call last):
  File "/Data/haikuporter/HaikuPorter/Main.py", line 40, in __init__
    self.run(args)
  File "/Data/haikuporter/HaikuPorter/Main.py", line 458, in run
    self._buildPort(port, True, self.packagesPath)
  File "/Data/haikuporter/HaikuPorter/Main.py", line 686, in _buildPort
    port.build(self.packagesPath, self.options.package, targetPath)
  File "/Data/haikuporter/HaikuPorter/Port.py", line 758, in build
    = RequiresUpdater(self.packages, requiredPackages)
  File "/Data/haikuporter/HaikuPorter/RequiresUpdater.py", line 30, in __init__
    self._providesManager.addProvidesFromPackage(package)
  File "/Data/haikuporter/HaikuPorter/ProvidesManager.py", line 40, in addProvidesFromPackage
    self._addPackageProvidesInfo(package.revisionedName, providesString)
  File "/Data/haikuporter/HaikuPorter/ProvidesManager.py", line 109, in _addPackageProvidesInfo
    if packageInfo.path in self._providesSourceMap:
AttributeError: 'unicode' object has no attribute 'path'
```

**Comment by diversys** [comment]
Might be a problem with huexpress recipe. Have you not pushed it yet?
