### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuporter#199]
After pulling haikuporter tree and haikuports tree, haikuporter gives me this:
```
~> haikuporter
dictionary changed size during iteration
```
**EDIT** this is on the gcc2h (did a pkgman full-sync before, rebooted, pulled (cleaned leftover source and downloads)) and then ran haikuporter

**Comment by Begasus** [comment]
Seems to be a python thing, @kallisti5 could you have a look here?

**Comment by Begasus** [comment]
On x86_64 it seems to be OK

**Comment by korli** [comment]
@Begasus for the time being you can point your HaikuPorter checkout to an older commit

**Comment by Begasus** [comment]
> @Begasus for the time being you can point your HaikuPorter checkout to an older commit

Tried that, but than I ran into "unsupported pickle protocol: 4"

**Comment by Begasus** [comment]
Just reverted to a previous commit, and renamed the repository folder, it's updating repository atm, so need to wait until that's finished to know if it worked

**Comment by korli** [comment]
> Tried that, but than I ran into "unsupported pickle protocol: 4"

remove any compiled pyc files?

**Comment by Begasus** [comment]
> > Tried that, but than I ran into "unsupported pickle protocol: 4"
> 
> remove any compiled pyc files?

Nope, didn't remove any files when running into that

**Comment by Begasus** [comment]
FWIW, @extrowerk had the same problem

**Comment by korli** [comment]
It might simply be that some generated files are in a serialised binary format, HaikuPorter should remove and regenerate them.

**Comment by Begasus** [comment]
Renaming the folder repository and re-populating the dependencies worked (after reverting to a previous commit)

**Comment by kallisti5** [comment]
weird, I haven't seen this one.

Could this be reproduced with debugging on in haikuporter?  (--debug)  it hides python traces without that flag.

**Comment by ambroff** [comment]
```
Checking if any dependency-infos need to be updated ...
Traceback (most recent call last):
  File "/Code/haikuporter/HaikuPorter/Main.py", line 38, in __init__
    self.run(args)
  File "/Code/haikuporter/HaikuPorter/Main.py", line 274, in run
    self._createRepositoryIfNeeded(self.options.quiet, self.options.verbose)
  File "/Code/haikuporter/HaikuPorter/Main.py", line 791, in _createRepositoryIfNeeded
    self.options.preserveFlags, quiet, verbose)
  File "/Code/haikuporter/HaikuPorter/Repository.py", line 68, in __init__
    self._updateRepository()
  File "/Code/haikuporter/HaikuPorter/Repository.py", line 490, in _updateRepository
    self._removeStalePortForPackageMappings(activePorts)
  File "/Code/haikuporter/HaikuPorter/Repository.py", line 549, in _removeStalePortForPackageMappings
    for packageId, portId in self._portIdForPackageId.items():
RuntimeError: dictionary changed size during iteration
```

Looks like in Python3 items doesn't return a copy of the items, so something like this fixes it.

```diff
➜  ~ cat foo.diff 
diff --git a/HaikuPorter/Repository.py b/HaikuPorter/Repository.py
index ba39dcc..9a56687 100644
--- a/HaikuPorter/Repository.py
+++ b/HaikuPorter/Repository.py
@@ -546,11 +546,11 @@ class Repository(object):
 		"""drops any port-for-package mappings that refer to non-existing or
 		   broken ports"""
 
-		for packageId, portId in self._portIdForPackageId.items():
+		for packageId, portId in tuple(self._portIdForPackageId.items()):
 			if portId not in activePorts:
 				del self._portIdForPackageId[packageId]
 
-		for packageName, portName in self._portNameForPackageName.items():
+		for packageName, portName in tuple(self._portNameForPackageName.items()):
 			if portName not in self._portVersionsByName:
 				del self._portNameForPackageName[packageName]
 				continue
```

**Comment by Begasus** [comment]
With the current PR it's OK on 64bit, on 32bit I still get:
```
~/haikuporter> hp album --debug
Traceback (most recent call last):
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 38, in __init__
    self.run(args)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 274, in run
    self._createRepositoryIfNeeded(self.options.quiet, self.options.verbose)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 791, in _createRepositoryIfNeeded
    self.options.preserveFlags, quiet, verbose)
  File "/boot/home/haikuporter/HaikuPorter/Repository.py", line 61, in __init__
    self._initAllPorts()
  File "/boot/home/haikuporter/HaikuPorter/Repository.py", line 301, in _initAllPorts
    for port in self._allPorts.values():
RuntimeError: dictionary changed size during iteration
```
